import { Inter } from "next/font/google";
import "./globals.css";
import { DefaultFooter, DefaultHeader } from "@/components/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apple Book Store ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultHeader />
        <main className=" dark:bg-gray-900">
        {children}
        </main>


        <DefaultFooter />
      </body>
    </html>
  );
}
